# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: 'en'

early_access: false

reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    # Ignore Claude Code agent/command configuration
    - '!.claude/**'
    # Ignore agent-os spec and planning files
    - '!agent-os/**'
    # Standard exclusions
    - '!**/dist/**'
    - '!**/*.snap'
    - '!**/package-lock.json'
  path_instructions:
    - path: '**/*.ts'
      instructions: |
        Review the TypeScript code for conformity with best practices. Ensure that:
        - The code adheres to Node.js best practices
        - The code follows existing patterns in the codebase
        - Error handling is comprehensive
        - Types are properly defined and used
  auto_review:
    enabled: true
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
    drafts: false
    base_branches:
      - 'main'

chat:
  auto_reply: true
