name: ✨ Feature Request
description: Suggest a new feature or enhancement for Nexus
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! We value your input in making Nexus better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: I'm frustrated when... or I need to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: I would like Nexus to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... but it doesn't work because...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - MCP Protocol Enhancement
        - Search Functionality
        - Configuration/Setup
        - Developer Experience
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Needed for my workflow
        - Critical - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples/Mockups
      description: Provide examples, mockups, or references to similar features
      placeholder: |
        Example usage:
        ```bash
        npx nexus-mcp --new-feature
        ```

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas for how this could be implemented?
      placeholder: This could be implemented by...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: This feature aligns with Nexus's goals of simplifying AI integration
          required: true
        - label: I have provided sufficient detail for the development team to understand the request
          required: true
