name: ❓ Question
description: Ask a question about using Nexus
title: '[Question]: '
labels: ['question', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Nexus? We're here to help!

        **Before asking:** Please check our [documentation](README.md) and search existing issues.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation/Setup
        - MCP Client Integration
        - Configuration
        - Troubleshooting
        - API Usage
        - Performance
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your use case or environment
      placeholder: |
        I'm trying to...
        My setup includes...
        I've already tried...

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
      placeholder: |
        I tried:
        1. Reading the documentation
        2. Searching existing issues
        3. Testing with different configurations

  - type: input
    id: client
    attributes:
      label: MCP Client
      description: Which MCP client are you using? (if applicable)
      placeholder: Claude Desktop, Cursor, etc.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your environment details (if applicable)
      placeholder: OS, Node.js version, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched the documentation and existing issues
          required: true
        - label: I have provided enough context for others to understand my question
          required: true
